apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: auto-check-service
  name: auto-check-service
spec:
  type: ClusterIP
  ports:
    - port: 8120
      targetPort: 8120
      protocol: TCP
  selector:
    io.kompose.service: auto-check-service