version: '3.1'
services:
  postgresqldb-educational-material:
    network_mode: bridge
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=educational_materials
    volumes:
      - postgres-data-educational-material:/home/art/postgres_microservices/educational_material_service
  educational-material-service:
    network_mode: bridge
    container_name: educational-material-service
    image: artiseasy/educational-material-service:latest
    build: ./
    expose:
      - 8100
    ports:
      - "8100:8100"
    depends_on:
      - postgresqldb-educational-material
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=educational_materials
      - DB_SERVER=postgresqldb-educational-material
    links:
      - postgresqldb-educational-material

volumes:
  postgres-data-educational-material: