apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: account-service
  name: account-service
spec:
  replicas: 2
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: account-service
    spec:
      containers:
      - env:
        - name: DB_SERVER
          value: postgresqldb-account
        - name: POSTGRES_DB
          value: accounts
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        image: artiseasy/account-service:latest
        name: account-service
        ports:
        - containerPort: 8090
        resources: {}
      restartPolicy: Always
  selector:
          matchLabels:
            io.kompose.service: account-service
status: {}
