apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: educational-material-service
  name: educational-material-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: educational-material-service
    spec:
      containers:
      - env:
        - name: DB_SERVER
          value: postgresqldb-educational-material
        - name: POSTGRES_DB
          value: educational_materials
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        image: artiseasy/educational-material-service:latest
        name: educational-material-service
        ports:
        - containerPort: 8100
        resources: {}
      restartPolicy: Always
  selector:
          matchLabels:
                  io.kompose.service: educational-material-service
status: {}
