apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: postgresqldb-educational-material
  name: postgresqldb-educational-material
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: postgresqldb-educational-material
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: educational_materials
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        image: postgres
        name: postgresqldb-educational-material
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /home/art/postgres_microservices/educational_material_service
          name: postgres-data-educational-material
      restartPolicy: Always
      volumes:
      - name: postgres-data-educational-material
        persistentVolumeClaim:
          claimName: postgres-data-educational-material
  selector:
          matchLabels:
                  io.kompose.service: postgresqldb-educational-material
status: {}
