apiVersion: v1
kind: Service
metadata:
  labels:
    name: rabbitmq
  name: rabbitmq
spec:
  type: NodePort
  ports:
    - port: 5672
      targetPort: 5672
      name: amqp
    - port: 15672
      targetPort: 15672
      nodePort: 31672
      name: http
  selector:
    name: rabbitmq
