version: '3.1'
services:
  postgresqldb-course-progress:
    network_mode: bridge
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=course-progress
    volumes:
      - postgres-data-account:/home/art/postgres_microservices/course_progress_service
  course-progress-service:
    network_mode: bridge
    container_name: course-progress-service
    image: artiseasy/course-progress-service:latest
    build: ./
    expose:
      - 8110
    ports:
      - "8110:8110"
    depends_on:
      - postgresqldb-course-progress
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=course-progress
      - DB_SERVER=postgresqldb-course-progress
    links:
      - postgresqldb-course-progress

volumes:
  postgres-data-account:
