apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: postgresqldb-course-progress
  name: postgresqldb-course-progress
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: postgresqldb-course-progress
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: course-progress
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        image: postgres
        name: postgresqldb-course-progress
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /home/art/postgres_microservices/course_progress_service
          name: postgres-data-course-progress
      restartPolicy: Always
      volumes:
      - name: postgres-data-course-progress
        persistentVolumeClaim:
          claimName: postgres-data-course-progress
  selector:
    matchLabels:
      io.kompose.service: postgresqldb-course-progress
status: {}
